openapi: "3.0.1"
info:
  title: "Azure Startup Sample Serverless Project - API"
  version: "2022-02-15T07:09:58Z"
servers:
  - url: "https://ukeme-alpha-api-mgmt.azure-api.net/{basePath}"
    variables:
      basePath:
        default: "/test"
paths:
  /v1/time:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                type: object
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: object
  /v1/images:
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                type: object
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: object
  /v1:
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: object
  /v1/greeting:
    get:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                type: object
    post:
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                type: object
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                type: object
