name: Deploy Infrastructure
run-name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      terraform-version:
        type: choice
        description: Terraform version to use
        options:
        - 1.9.2
        - 1.8.5
      environment:
        description: Environment to deploy to
        type: environment
      terraform-log-level:
        description: Terraform log level
        type: choice
        default: WARN
        options:
        - TRACE
        - DEBUG
        - INFO
        - WARN
        - ERROR

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: "true"

jobs:
  plan-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform v${{ inputs.terraform-version }}
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Azure Login via OIDC
      id: azure_login
      uses: azure/login@v2
      with:
        client-id: ${{ env.ARM_CLIENT_ID }}
        tenant-id: ${{ env.ARM_TENANT_ID }}
        subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

    - name: Initializing Terraform
      working-directory: ./examples
      run: |
        terraform init -input=false
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_LOG: ${{ inputs.terraform-log-level }}

    - name: Generate Terraform Plan
      working-directory: ./examples
      run: |
        terraform plan -input=false
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        TF_LOG: ${{ inputs.terraform-log-level }}
